language: python
python:
  - 2.7

install:
  - python bootstrap.py -d
  - bin/buildout

script:
  - bin/nosetests
  - bin/mrbob -O collective.foo --config test_answers.ini ./bobtemplates/plone
  - bin/mrbob -O collective.foo.bar --config test_answers_nested.ini ./bobtemplates/plone_nested

after_success:
 - pip install python-coveralls==2.4.0
 - coveralls

notifications:
 email:
  - franck.o.ngaha@gmail.com
