language: python
python:
  - 2.7

install:
  - python bootstrap.py
  - bin/buildout

script:
  - bin/nosetests
  - bin/mrbob -O plone.foo --config test_answers.ini ./bobtemplates/plone
  - bin/mrbob -O plone.foo.bar --config test_answers_nested.ini ./bobtemplates/plone_nested

notifications:
 email:
  - franck.o.ngaha@gmail.com
